apiVersion: apps/v1
kind: Deployment
metadata:
  name: bigdata-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: fastapi
        image: langhae/bigdata:demo
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "128Mi"
        #     cpu: "500m"
        envFrom:
          - secretRef:
              name: fastapi-envs        
        ports:
        - containerPort: 80
