namespace: pro
namePrefix: pro-
commonLabels:
  app: pro-ai
secretGenerator:
- name: fastapi-envs
  literals:
  - DB=mysql+pymysql
  - MYSQL_USER=langhae
  - MYSQL_PASSWORD=1234qwer
  - MYSQL_DATABASE=db
  - MYSQL_HOST=pro-rds-svc.pro
  - POST_URI=faceimage
resources:
- deployment.yaml
- service.yaml