apiVersion: v1
kind: Service
metadata:
  name: rds-svc
spec:
  type: ExternalName
  ports:
  - port: 3306
    targetPort: 3306
  externalName: database-2.czxxrvenvmxq.ap-southeast-2.rds.amazonaws.com