apiVersion: apps/v1
kind: Deployment
metadata:
  name: media-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: fastapi
        image: langhae/media:demo
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "521Mi"
        #     cpu: "1000m"
        envFrom:
          - secretRef:
              name: fastapi-envs
        ports:
        - containerPort: 80
