namespace: dev
namePrefix: dev-
commonLabels:
  app: dev-media
secretGenerator:
- name: fastapi-envs
  literals:
  - DB=mysql+pymysql
  - MYSQL_USER=langhae
  - MYSQL_PASSWORD=1234qwer
  - MYSQL_DATABASE=db
  - MYSQL_HOST=db-0.mysql-svc
  - POST_AI_URI=http://dev-ai-svc.dev/faceimage
  - POST_BIGDATA_URI=http://dev-bigdata-svc.dev/recommend
  - POST_URI=post_image
resources:
- deployment.yaml
- service.yaml